# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ami/projects/Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ami/projects/Test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ami/projects/Test/CMakeFiles /home/ami/projects/Test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ami/projects/Test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

Cell.o: Cell.cpp.o

.PHONY : Cell.o

# target to build an object file
Cell.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Cell.cpp.o
.PHONY : Cell.cpp.o

Cell.i: Cell.cpp.i

.PHONY : Cell.i

# target to preprocess a source file
Cell.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Cell.cpp.i
.PHONY : Cell.cpp.i

Cell.s: Cell.cpp.s

.PHONY : Cell.s

# target to generate assembly for a file
Cell.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Cell.cpp.s
.PHONY : Cell.cpp.s

Factory.o: Factory.cpp.o

.PHONY : Factory.o

# target to build an object file
Factory.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Factory.cpp.o
.PHONY : Factory.cpp.o

Factory.i: Factory.cpp.i

.PHONY : Factory.i

# target to preprocess a source file
Factory.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Factory.cpp.i
.PHONY : Factory.cpp.i

Factory.s: Factory.cpp.s

.PHONY : Factory.s

# target to generate assembly for a file
Factory.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Factory.cpp.s
.PHONY : Factory.cpp.s

FormulaCell.o: FormulaCell.cpp.o

.PHONY : FormulaCell.o

# target to build an object file
FormulaCell.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/FormulaCell.cpp.o
.PHONY : FormulaCell.cpp.o

FormulaCell.i: FormulaCell.cpp.i

.PHONY : FormulaCell.i

# target to preprocess a source file
FormulaCell.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/FormulaCell.cpp.i
.PHONY : FormulaCell.cpp.i

FormulaCell.s: FormulaCell.cpp.s

.PHONY : FormulaCell.s

# target to generate assembly for a file
FormulaCell.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/FormulaCell.cpp.s
.PHONY : FormulaCell.cpp.s

NoneCell.o: NoneCell.cpp.o

.PHONY : NoneCell.o

# target to build an object file
NoneCell.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NoneCell.cpp.o
.PHONY : NoneCell.cpp.o

NoneCell.i: NoneCell.cpp.i

.PHONY : NoneCell.i

# target to preprocess a source file
NoneCell.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NoneCell.cpp.i
.PHONY : NoneCell.cpp.i

NoneCell.s: NoneCell.cpp.s

.PHONY : NoneCell.s

# target to generate assembly for a file
NoneCell.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NoneCell.cpp.s
.PHONY : NoneCell.cpp.s

NumberCell.o: NumberCell.cpp.o

.PHONY : NumberCell.o

# target to build an object file
NumberCell.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NumberCell.cpp.o
.PHONY : NumberCell.cpp.o

NumberCell.i: NumberCell.cpp.i

.PHONY : NumberCell.i

# target to preprocess a source file
NumberCell.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NumberCell.cpp.i
.PHONY : NumberCell.cpp.i

NumberCell.s: NumberCell.cpp.s

.PHONY : NumberCell.s

# target to generate assembly for a file
NumberCell.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/NumberCell.cpp.s
.PHONY : NumberCell.cpp.s

Parser.o: Parser.cpp.o

.PHONY : Parser.o

# target to build an object file
Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Parser.cpp.o
.PHONY : Parser.cpp.o

Parser.i: Parser.cpp.i

.PHONY : Parser.i

# target to preprocess a source file
Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Parser.cpp.i
.PHONY : Parser.cpp.i

Parser.s: Parser.cpp.s

.PHONY : Parser.s

# target to generate assembly for a file
Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Parser.cpp.s
.PHONY : Parser.cpp.s

ReversePolandNotation.o: ReversePolandNotation.cpp.o

.PHONY : ReversePolandNotation.o

# target to build an object file
ReversePolandNotation.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/ReversePolandNotation.cpp.o
.PHONY : ReversePolandNotation.cpp.o

ReversePolandNotation.i: ReversePolandNotation.cpp.i

.PHONY : ReversePolandNotation.i

# target to preprocess a source file
ReversePolandNotation.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/ReversePolandNotation.cpp.i
.PHONY : ReversePolandNotation.cpp.i

ReversePolandNotation.s: ReversePolandNotation.cpp.s

.PHONY : ReversePolandNotation.s

# target to generate assembly for a file
ReversePolandNotation.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/ReversePolandNotation.cpp.s
.PHONY : ReversePolandNotation.cpp.s

Source.o: Source.cpp.o

.PHONY : Source.o

# target to build an object file
Source.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Source.cpp.o
.PHONY : Source.cpp.o

Source.i: Source.cpp.i

.PHONY : Source.i

# target to preprocess a source file
Source.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Source.cpp.i
.PHONY : Source.cpp.i

Source.s: Source.cpp.s

.PHONY : Source.s

# target to generate assembly for a file
Source.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Source.cpp.s
.PHONY : Source.cpp.s

StringCell.o: StringCell.cpp.o

.PHONY : StringCell.o

# target to build an object file
StringCell.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/StringCell.cpp.o
.PHONY : StringCell.cpp.o

StringCell.i: StringCell.cpp.i

.PHONY : StringCell.i

# target to preprocess a source file
StringCell.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/StringCell.cpp.i
.PHONY : StringCell.cpp.i

StringCell.s: StringCell.cpp.s

.PHONY : StringCell.s

# target to generate assembly for a file
StringCell.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/StringCell.cpp.s
.PHONY : StringCell.cpp.s

UserInterface.o: UserInterface.cpp.o

.PHONY : UserInterface.o

# target to build an object file
UserInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/UserInterface.cpp.o
.PHONY : UserInterface.cpp.o

UserInterface.i: UserInterface.cpp.i

.PHONY : UserInterface.i

# target to preprocess a source file
UserInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/UserInterface.cpp.i
.PHONY : UserInterface.cpp.i

UserInterface.s: UserInterface.cpp.s

.PHONY : UserInterface.s

# target to generate assembly for a file
UserInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/UserInterface.cpp.s
.PHONY : UserInterface.cpp.s

Variant.o: Variant.cpp.o

.PHONY : Variant.o

# target to build an object file
Variant.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Variant.cpp.o
.PHONY : Variant.cpp.o

Variant.i: Variant.cpp.i

.PHONY : Variant.i

# target to preprocess a source file
Variant.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Variant.cpp.i
.PHONY : Variant.cpp.i

Variant.s: Variant.cpp.s

.PHONY : Variant.s

# target to generate assembly for a file
Variant.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/Variant.cpp.s
.PHONY : Variant.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Test"
	@echo "... Cell.o"
	@echo "... Cell.i"
	@echo "... Cell.s"
	@echo "... Factory.o"
	@echo "... Factory.i"
	@echo "... Factory.s"
	@echo "... FormulaCell.o"
	@echo "... FormulaCell.i"
	@echo "... FormulaCell.s"
	@echo "... NoneCell.o"
	@echo "... NoneCell.i"
	@echo "... NoneCell.s"
	@echo "... NumberCell.o"
	@echo "... NumberCell.i"
	@echo "... NumberCell.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... ReversePolandNotation.o"
	@echo "... ReversePolandNotation.i"
	@echo "... ReversePolandNotation.s"
	@echo "... Source.o"
	@echo "... Source.i"
	@echo "... Source.s"
	@echo "... StringCell.o"
	@echo "... StringCell.i"
	@echo "... StringCell.s"
	@echo "... UserInterface.o"
	@echo "... UserInterface.i"
	@echo "... UserInterface.s"
	@echo "... Variant.o"
	@echo "... Variant.i"
	@echo "... Variant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

